name: Run Free Trial Instance Data Population

on:
  workflow_dispatch:
    inputs:
      instance_url:
        description: 'PlexTrac instance URL'
        required: true
        type: string
      username:
        description: 'Username'
        required: true
        type: string
      password:
        description: 'Password'
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Mask Password
        shell: bash
        run: |
          API_PASSWORD=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH)
          echo ::add-mask::$API_PASSWORD
          echo API_PASSWORD=$API_PASSWORD >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "Pipfile"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --deploy

      - name: Run script
        env:
          INSTANCE_URL: ${{ github.event.inputs.instance_url }}
          USERNAME: ${{ github.event.inputs.username }}
          PASSWORD: ${{ env.API_PASSWORD }}
        run: |
          pipenv run python main.py
