name: Run Free Trial Instance Data Population

on:
  workflow_dispatch:
    inputs:
      instance_url:
        description: 'PlexTrac instance URL'
        required: true
        type: string
      username:
        description: 'Username'
        required: true
        type: string
      password:
        description: 'Password'
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --system --deploy

      - name: Run script
        env:
          INSTANCE_URL: ${{ github.event.inputs.instance_url }}
          USERNAME: ${{ github.event.inputs.username }}
          PASSWORD: ${{ github.event.inputs.password }}
        run: |
          python main.py
